services:
  api:
    container_name: green_jobs_backend
    restart: on-failure
    depends_on:
      - greenjobs_db
    env_file:
      - .env

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"

  greenjobs_db:
    image: bitnami/postgresql:15.3.0-debian-11-r85
    ports:
      - "5432:5432"
    volumes:
      - green_jobs-db:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=green_jobs_db

volumes:
  green_jobs-db:
