services:
  test_db:
    image: bitnami/postgresql:15.3.0-debian-11-r85
    container_name: skillsync-test_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=skillsync_test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - test_db_data:/bitnami/postgresql

  test_redis:
    image: redis:7.0-alpine
    container_name: skillsync-test_redis
    ports:
      - "6380:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  test_db_data:
