services:
  api:
    container_name: skillsync_backend
    restart: on-failure
    depends_on:
      skillsync_db:
        condition: service_healthy
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/skillsync_backend
      - ./app:/skillsync_backend/app
      - ./alembic:/skillsync_backend/alembic
      - ./core:/skillsync_backend/core
    environment:
      - PYTHONPATH=/skillsync_backend
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - skillsync_network

  skillsync_db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - skillsync_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=skillsync_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - skillsync_network
    restart: unless-stopped

volumes:
  skillsync_db:
    name: skillsync_db_data

networks:
  skillsync_network:
    name: skillsync_network
