services:
  api:
    container_name: skillsync_backend
    restart: on-failure
    depends_on:
      - skillsync_db
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/skillsync_backend
      - ./app:/skillsync_backend/app
    environment:
      - PYTHONPATH=/skillsync_backend
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  skillsync_db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - skillsync_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=skillsync_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  skillsync_db:
