// "use client";

import {
  type IconProps,
  ArrowCircleRight,
  ArrowsDownUp,
  ArrowLeft,
  ArrowLineDown,
  ArrowSquareOut,
  ArrowUUpLeft,
  ArrowUUpRight,
  Bank,
  Barricade,
  Basketball,
  BellSimple,
  Bridge,
  Briefcase,
  Binoculars,
  BookmarkSimple,
  Books,
  Buildings,
  CalendarBlank,
  CalendarX,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Carrot,
  CarProfile,
  Check,
  CircleNotch,
  Circuitry,
  ChartBarHorizontal,
  ChatCircleDots,
  ClockCounterClockwise,
  Confetti,
  Drop,
  Eye,
  EyeSlash,
  Export,
  FadersHorizontal,
  FirstAidKit,
  Flag,
  Flask,
  Folder,
  Gear,
  Handshake,
  Heart,
  HouseLine,
  HouseSimple,
  Mountains,
  Notebook,
  Notepad,
  IconWeight,
  Lightning,
  LinkSimple,
  ListBullets,
  ListChecks,
  ListNumbers,
  Minus,
  Warning,
  WarningDiamond,
  CheckCircle,
  Info,
  Nut,
  Palette,
  PaperPlaneTilt,
  PencilSimple,
  PencilSimpleLine,
  PiggyBank,
  Plus,
  PlusCircle,
  SealCheck,
  SidebarSimple,
  SignOut,
  SmileyMeh,
  SmileyNervous,
  SmileyBlank,
  Smiley,
  SmileyXEyes,
  Star,
  Television,
  TextAlignLeft,
  TextAlignRight,
  TextAlignCenter,
  TextB,
  TextItalic,
  TextStrikethrough,
  TextUnderline,
  Trash,
  Tree,
  User,
  UploadSimple,
  Warehouse,
  X,
  XCircle
} from '@phosphor-icons/react';
import { createElement } from 'react';
import { CircuitryIcon } from './circuitry-icon';

export const PhosphorIconList = {
  ArrowCircleRight,
  ArrowsDownUp,
  ArrowLeft,
  ArrowLineDown,
  ArrowSquareOut,
  ArrowUUpLeft,
  ArrowUUpRight,
  Bank,
  Barricade,
  BellSimple,
  Binoculars,
  Basketball,
  BookmarkSimple,
  Books,
  Bridge,
  Briefcase,
  Buildings,
  CalendarBlank,
  CalendarX,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Carrot,
  CarProfile,
  Check,
  CircleNotch,
  Circuitry,
  ChartBarHorizontal,
  ChatCircleDots,
  ClockCounterClockwise,
  Confetti,
  Drop,
  Handshake,
  Heart,
  HouseLine,
  HouseSimple,
  Export,
  Eye,
  EyeSlash,
  FadersHorizontal,
  FirstAidKit,
  Flag,
  Flask,
  Folder,
  Gear,
  Minus,
  Mountains,
  Notebook,
  Notepad,
  Nut,
  CheckCircle,
  Info,
  Lightning,
  LinkSimple,
  ListBullets,
  ListChecks,
  ListNumbers,
  Palette,
  PaperPlaneTilt,
  PencilSimple,
  PencilSimpleLine,
  PiggyBank,
  Plus,
  PlusCircle,
  SealCheck,
  SidebarSimple,
  SignOut,
  Smiley,
  SmileyBlank,
  SmileyMeh,
  SmileyNervous,
  SmileyXEyes,
  Star,
  Television,
  TextAlignLeft,
  TextAlignRight,
  TextAlignCenter,
  TextB,
  TextItalic,
  TextStrikethrough,
  TextUnderline,
  Trash,
  Tree,
  UploadSimple,
  User,
  Warehouse,
  Warning,
  WarningDiamond,
  X,
  XCircle
};

type IconNames = keyof typeof PhosphorIconList;
export type IconVariant = `${IconNames}_${IconWeight}`;

export interface PhosphorIconProps extends IconProps {
  iconVariant: IconVariant;
  className?: string;
}

export function PhosphorIcon({
  iconVariant,
  size = 24,
  className
}: PhosphorIconProps) {
  const iconProps = iconVariant.split('_');
  const iconName = iconProps[0] as IconNames;
  const iconWeight = iconProps[1] as IconWeight;
  return (
    <>
      {createElement(PhosphorIconList[iconName], {
        size: size,
        weight: iconWeight,
        className: className
      })}
    </>
  );
}
