"""initial_db_setup

Revision ID: 709dd6335ea5
Revises:
Create Date: 2025-06-04 00:37:53.567096

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "709dd6335ea5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("account_tier", sa.String(length=32), server_default="free", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_base_users_id"), "base_users", ["id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("size", sa.String(), nullable=True),
        sa.Column("no_of_employees", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("overview", sa.String(), nullable=True),
        sa.Column("benefits", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("select_career_path", sa.String(), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["base_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_careerforge",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("base_user_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("profile_picture_url", sa.String(), nullable=True),
        sa.Column("profile_strength", sa.Integer(), server_default="0", nullable=True),
        sa.Column("achievement_score", sa.Integer(), server_default="0", nullable=True),
        sa.Column("parsed_resume", sa.JSON(), nullable=True),
        sa.Column("skill_vector", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("skills", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("career_stage", sa.String(length=64), nullable=True),
        sa.Column("industry_focus", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("interests", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("current_career", sa.String(), nullable=True),
        sa.Column("job_search_phase", sa.String(), nullable=True),
        sa.Column("current_job_title", sa.String(), nullable=True),
        sa.Column("career_summary", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("ethnicity", sa.String(), nullable=True),
        sa.Column("nationality", sa.String(), nullable=True),
        sa.Column("birthday", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("linkedin_url", sa.String(), nullable=True),
        sa.Column("instagram_url", sa.String(), nullable=True),
        sa.Column("facebook_url", sa.String(), nullable=True),
        sa.Column("x_twitter_url", sa.String(), nullable=True),
        sa.Column("personal_website_url", sa.String(), nullable=True),
        sa.Column("github_url", sa.String(), nullable=True),
        sa.Column("background_image_url", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_user_id"],
            ["base_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_careerforge_email"), "user_careerforge", ["email"], unique=True)
    op.create_index(op.f("ix_user_careerforge_id"), "user_careerforge", ["id"], unique=False)
    op.create_table(
        "cover_letters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("generated_output", sa.String(length=4096), nullable=True),
        sa.Column("style", sa.String(length=128), nullable=True),
        sa.Column("tone", sa.JSON(), nullable=True),
        sa.Column("topics", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cover_letters_id"), "cover_letters", ["id"], unique=False)
    op.create_table(
        "experiences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("position_title", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("skills", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("achievements", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("employment_type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "milestones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("milestone_type", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("achievement_points", sa.Integer(), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("proof_url", sa.String(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("project_title", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=4096), nullable=True),
        sa.Column("technologies", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("project_url", sa.String(), nullable=True),
        sa.Column("github_url", sa.String(), nullable=True),
        sa.Column("showcase_priority", sa.Integer(), nullable=True),
        sa.Column("visibility", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("file_url", sa.String(length=512), nullable=False),
        sa.Column("file_type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_files_id"), "user_files", ["id"], unique=False)
    op.create_table(
        "user_talenthub",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("base_user_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("profile_picture_url", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("hiring_capacity", sa.Integer(), nullable=True),
        sa.Column("recruitment_focus", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("verification_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_method", sa.String(), nullable=True),
        sa.Column("talent_pipeline_size", sa.Integer(), server_default="0", nullable=True),
        sa.Column("success_metrics", sa.JSON(), nullable=True),
        sa.Column("notification_preferences", sa.JSON(), nullable=True),
        sa.Column("candidate_scoring_weights", sa.JSON(), nullable=True),
        sa.Column("interview_availability", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_user_id"],
            ["base_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_talenthub_email"), "user_talenthub", ["email"], unique=True)
    op.create_index(op.f("ix_user_talenthub_id"), "user_talenthub", ["id"], unique=False)
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("recruiter_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("job_category", sa.String(), nullable=True),
        sa.Column("position_type", sa.String(), nullable=True),
        sa.Column("level_of_experience", sa.String(), nullable=True),
        sa.Column("role_description", sa.String(), nullable=True),
        sa.Column("education_level", sa.String(), nullable=True),
        sa.Column("special_educational_requirements", sa.String(), nullable=True),
        sa.Column("workplace_type", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("pay_type", sa.String(), nullable=True),
        sa.Column("minimum_pay", sa.Integer(), nullable=True),
        sa.Column("maximum_pay", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("required_skills", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("preferred_skills", sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recruiter_id"],
            ["user_talenthub.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("position_id", sa.UUID(), nullable=True),
        sa.Column("activity", sa.String(length=512), nullable=True),
        sa.Column("reaction", sa.String(length=512), nullable=True),
        sa.Column("notes", sa.String(length=4096), nullable=True),
        sa.Column("stage", sa.JSON(), nullable=True),
        sa.Column("is_favourite", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_applications")
    op.drop_table("positions")
    op.drop_index(op.f("ix_user_talenthub_id"), table_name="user_talenthub")
    op.drop_index(op.f("ix_user_talenthub_email"), table_name="user_talenthub")
    op.drop_table("user_talenthub")
    op.drop_index(op.f("ix_user_files_id"), table_name="user_files")
    op.drop_table("user_files")
    op.drop_table("portfolios")
    op.drop_table("milestones")
    op.drop_table("experiences")
    op.drop_index(op.f("ix_cover_letters_id"), table_name="cover_letters")
    op.drop_table("cover_letters")
    op.drop_index(op.f("ix_user_careerforge_id"), table_name="user_careerforge")
    op.drop_index(op.f("ix_user_careerforge_email"), table_name="user_careerforge")
    op.drop_table("user_careerforge")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_base_users_id"), table_name="base_users")
    op.drop_table("base_users")
    # ### end Alembic commands ###
