"""initial_db_setup

Revision ID: b676c8888301
Revises:
Create Date: 2025-06-12 03:49:06.602426

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b676c8888301"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_careerforge",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("base_user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("gender", sa.String(length=32), nullable=True),
        sa.Column("ethnicity", sa.String(length=32), nullable=True),
        sa.Column("nationality", sa.String(length=64), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("linkedin_url", sa.String(length=512), nullable=True),
        sa.Column("github_url", sa.String(length=512), nullable=True),
        sa.Column("x_twitter_url", sa.String(length=512), nullable=True),
        sa.Column("personal_website_url", sa.String(length=512), nullable=True),
        sa.Column("current_career", sa.String(length=512), nullable=True),
        sa.Column("job_search_phase", sa.String(length=512), nullable=True),
        sa.Column("skills", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("interests", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("career_summary", sa.String(length=4096), nullable=True),
        sa.Column("birthday", sa.String(length=32), nullable=True),
        sa.Column("current_job_title", sa.String(length=512), nullable=True),
        sa.Column("profile_picture_url", sa.String(length=512), nullable=True),
        sa.Column("background_image_url", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_user_id"],
            ["base_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_careerforge_email"), "user_careerforge", ["email"], unique=True)
    op.create_table(
        "user_talenthub",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("base_user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("gender", sa.String(length=32), nullable=True),
        sa.Column("nationality", sa.String(length=64), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("personal_website_url", sa.String(length=512), nullable=True),
        sa.Column("profile_picture_url", sa.String(length=512), nullable=True),
        sa.Column("current_job_title", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_user_id"],
            ["base_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_talenthub_email"), "user_talenthub", ["email"], unique=True)
    op.create_table(
        "cover_letters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("generated_output", sa.String(length=4096), nullable=True),
        sa.Column("style", sa.String(length=128), nullable=True),
        sa.Column("tone", sa.JSON(), nullable=True),
        sa.Column("topics", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cover_letters_id"), "cover_letters", ["id"], unique=False)
    op.create_table(
        "experiences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("position_title", sa.String(length=128), nullable=False),
        sa.Column("company_name", sa.String(length=128), nullable=False),
        sa.Column("employment_type", sa.String(length=128), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.Column("start_month", sa.INTEGER(), nullable=True),
        sa.Column("start_year", sa.INTEGER(), nullable=True),
        sa.Column("end_month", sa.INTEGER(), nullable=True),
        sa.Column("end_year", sa.INTEGER(), nullable=True),
        sa.Column("logo_url", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiences_id"), "experiences", ["id"], unique=False)
    op.create_table(
        "milestones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("tasks", sa.JSON(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), server_default="false", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_milestones_id"), "milestones", ["id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=128), nullable=False),
        sa.Column("size", sa.String(length=32), nullable=False),
        sa.Column("no_of_employees", sa.INTEGER(), nullable=True),
        sa.Column("is_bipoc_owned", sa.Boolean(), nullable=True),
        sa.Column("location", sa.String(length=128), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("overview", sa.String(length=4096), nullable=True),
        sa.Column("benefits", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("select_a_pathway", sa.String(length=512), nullable=True),
        sa.Column("logo_url", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_talenthub.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_table(
        "user_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("file_url", sa.String(length=512), nullable=False),
        sa.Column("file_type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("job_category", sa.String(length=128), nullable=False),
        sa.Column("position_type", sa.String(length=128), nullable=False),
        sa.Column("level_of_experience", sa.String(length=512), nullable=False),
        sa.Column("role_description", sa.String(length=4096), nullable=True),
        sa.Column("education_level", sa.String(length=512), nullable=True),
        sa.Column("special_educational_requirements", sa.String(length=2048), nullable=True),
        sa.Column("workplace_type", sa.String(length=512), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("pay_type", sa.String(length=64), nullable=True),
        sa.Column("minimum_pay", sa.Float(), nullable=True),
        sa.Column("maximum_pay", sa.Float(), nullable=True),
        sa.Column("pay_frequency", sa.String(length=64), nullable=True),
        sa.Column("closing_date", sa.String(length=64), nullable=True),
        sa.Column("external_link", sa.String(length=512), nullable=True),
        sa.Column("required_files", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("primary_responsibilities", sa.String(length=4096), nullable=True),
        sa.Column("required_qualifications", sa.String(length=4096), nullable=True),
        sa.Column("desired_qualifications", sa.String(length=4096), nullable=True),
        sa.Column("compensation_benefits", sa.String(length=4096), nullable=True),
        sa.Column("show_recruiter", sa.Boolean(), server_default="false", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_talenthub.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_positions_id"), "positions", ["id"], unique=False)
    op.create_table(
        "tracked_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("activity", sa.String(length=512), nullable=True),
        sa.Column("reaction", sa.String(length=512), nullable=True),
        sa.Column("notes", sa.String(length=4096), nullable=True),
        sa.Column("stage", sa.JSON(), nullable=True),
        sa.Column("is_favourite", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_careerforge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracked_jobs_id"), "tracked_jobs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracked_jobs_id"), table_name="tracked_jobs")
    op.drop_table("tracked_jobs")
    op.drop_index(op.f("ix_positions_id"), table_name="positions")
    op.drop_table("positions")
    op.drop_table("user_files")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_milestones_id"), table_name="milestones")
    op.drop_table("milestones")
    op.drop_index(op.f("ix_experiences_id"), table_name="experiences")
    op.drop_table("experiences")
    op.drop_index(op.f("ix_cover_letters_id"), table_name="cover_letters")
    op.drop_table("cover_letters")
    op.drop_index(op.f("ix_user_talenthub_email"), table_name="user_talenthub")
    op.drop_table("user_talenthub")
    op.drop_index(op.f("ix_user_careerforge_email"), table_name="user_careerforge")
    op.drop_table("user_careerforge")
    op.drop_table("base_users")
    # ### end Alembic commands ###
